export enum fireBaseConfigType {
  SAVE_IOS_FORCE_UPDATE = 'SAVE_IOS_FORCE_UPDATE',
  SAVE_ANDROID_FORCE_UPDATE = 'SAVE_ANDROID_FORCE_UPDATE',
  SAVE_IOS_VERSION_NUMBER = 'SAVE_IOS_VERSION_NUMBER',
  SAVE_ANDROID_VERSION_NUMBER = 'SAVE_ANDROID_VERSION_NUMBER',
  EXCLUDE_RESTAURANTS = 'EXCLUDE_RESTAURANTS',
  SAVE_CONFIG = 'SAVE_CONFIG'
}
