export enum newUserType {
  NEW_USER_SUCCESS = 'NEW_USER_SUCCESS',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_VIEWED_WELCOME_SCREEN = 'USER_VIEWED_WELCOME_SCREEN',
  SET_ONBOARDED = 'SET_ONBOARDED',
  SET_REWARDS_ONBOARDED = 'SET_REWARDS_ONBOARDED',
}
