export const strings = {
  enter_first_name: 'Enter First Name',
  enter_last_name: 'Enter Last Name',
  enter_email: 'Enter Email Address',
  enter_password: 'Enter Password',
  current_password: 'Current Password',
  confirm_password: 'Confirm Password',
  mobile_phone: 'Enter Mobile Number',
  new_password: 'New Password',
  general_msg: 'This field is required*',
  update_bag: 'Update Bag',
  add_to_bag: 'Add To Bag',
  enter_current_password: 'Enter Current Password',
  enter_new_password: 'Enter New Password',
  enter_confirm_password: 'Enter Password Again',

  invite_code: 'Invite Code (Optional)',
  birthday: 'Birthday',
  fav_locations: 'Favorite Location',
  title: 'SOMETHING WENT WRONG!',
  friendlySubtitle:
    "Uh-oh! We've hit a snag. Our app has encountered an unexpected error, We are working on it. \nThank you for your patience!.",
  reset: 'Take Me Home',
  traceTitle: 'Error from %{name} stack', // @demo remove-current-line
  sign_in: 'SIGN IN',
  create_an_account: 'Create Account',
  sign_in_: 'Sign in',
  sign_in_for_rewards: "Sign in for Rubio's MyRewards",
  sign_in_with_facebook: 'Sign in with Facebook',
  forgot_password: 'Forgot Password?',
  forgot_password2: 'Forgot Password',
  continue_as_guest: 'Continue as guest',
  forgot_password_info:
    'Enter your email below and to receive instructions to reset your password!',
  reset_password: 'Reset Password',
  perms_app_name: "Rubio's Coastal Grill",
  perms_message: "Please allow Rubio's Coastal Grill to use your location.",
  ask_me_later: 'Ask Me Later',
  cancel: 'Cancel',
  ok: 'OK',
  search_location_text: 'City, Zip Code, State',
  term1: 'I agree to the',
  term2: "Rubio's terms and conditions",
  term3: 'and',
  privacy_policy: 'privacy policy',
  password_required: 'Password is required.',
  password_invalid: 'Password must match the requirements.',
  email_required: 'Email is required',
  email_invalid: 'Please enter a valid email',
  confirm_password_required: 'Confirm Password is required',
  confirm_password_invalid: 'Passwords must match',
  first_name_required: 'First Name is required',
  last_name_required: 'Last Name is required',
  fav_loc_required: 'Favourite Location is required',
  phone_invalid: 'Enter a valid number',
  phone_required: 'Phone is required',
  term_required: 'Term and conditions must be accepted',
  submit: 'Submit',
  rest_search_placeholder: 'Enter State City or Zipcode here...',
  phone_number: 'Enter Phone Number',
  email_updates_text: "I agree to receive marketing communications from Rubio's.",
  vehicle_model: 'Vehicle Model*',
  vehicle_make: 'Vehicle Make*',
  vehicle_color: 'Vehicle Color*',
  edit_tip_amount: 'Edit Amount',
  enter_coupon_code: 'Enter Code',
  confirm: 'Confirm',
  confirm_your_delivery_address: 'Confirm Your Delivery Address',
  street_address: 'Street address',
  apt_floor_suite_building_companyaddress:
    'Apt, Floor, Suite, Building, Company Address - Optional',
  city: 'City',
  postal_code: 'Postal Code',
  required_street_address: 'Required street address',
  required_city: 'Required City',
  required_postcode: 'Required valid Postalcode',
  apply: 'Apply',
  points: 'Points',
  apply_rewards: 'APPLY REWARDS',
  select_a_delivery_address: 'Select a delivery address.',
  add_new_address: '+ Add new address',
  delivery_address: 'Delivery Address',
  add_address: 'Add address',
  make_default_delivery_address: 'Make default delivery address',
  confirm_address: 'Confirm Address',
  select: 'Select',
  edit: 'Edit',
  delivery_is_unavailable_for_this_address: 'Delivery is unavailable for this address',
  no_restaurant_found: 'No restaurant found',
  duplicate: 'Duplicate',
  remove: 'Remove',
  add_new_product: 'Add New Product',
  checkout: 'Checkout',
  delivery_is_available_for_this_address: 'DELIVERY IS AVAILABLE FOR THIS ADDRESS',
  delivery_not_available_for_this_address: 'DELIVERY NOT AVAILABLE FOR THIS ADDRESS',
  start_order: 'Start Order',
  postal_code_must_be_of_five_characters: 'Postal code must be of 5 characters',
  scan_qr_code: 'Please scan the QR code below at the register to redeem your reward.',
  how_to_redeem: 'HOW TO REDEEM YOUR REWARDS',
  in_restaurant_orders: 'IN-RESTAURANT ORDERS',
  online_app_order: 'ONLINE/APP ORDERS',
  in_restaurant_orders_des:
    'Click "Redeem in Restaurant" above and then scan the QR code at the register.',
  online_app_order_des:
    'Select from your Available ApplyRewards on the checkout screen to apply the reward.\n' +
    '\n' +
    'NOTE: Please be sure to add the free menu item to your order before applying the reward.',
  check_in: 'Chick In',
  check_in_des_1:
    'To check in at the restaurant, scan the QR code below at the register.\n' +
    '\n' +
    'If you order online, you are automatically checked in.',
  forgot_to_checkout: 'FORGOT TO CHECK IN?',
  check_in_des_2:
    'If you did not check in at the restaurant, you may enter the Rubio’s ApplyRewards barcode number located at the bottom of your receipt.\n' +
    '\n' +
    'Receipt codes must be scanned or manually entered within 48 hours of purchase.',
  check_in_des_3:
    'Please enter the 12 or 13 digit numeric barcode at the bottom of your receipt.\n' +
    '\n' +
    'Please ensure that you enter any leading zeroes that may appear in the barcode. e.g. 0600101234124',
  reward_sub_title: 'Click on a reward below only if you are redeeming in-store.',
  no_rewards_msg:
    "No rewards available. Keep checking in and we'll let you know when it's time to be rewarded.",
  delivery_is_not_available_at_this_time: 'Delivery is not available at this time',
  please_enter_your_full_delivery_address: 'Please enter your full delivery address.',
  fav_1: 'Do You Really Want To UnFavorite The Order?',
  no_fav_orders: 'You don’t have any favorite orders.',
  fav_name_required: 'Favorite Name is required',
  save_as_fav: 'Save Order as favorite ',
  fav_name: 'Favorite Name',
  no_recent_orders: "You don't have any recent orders",
  replace_reward:
    'Only 1 reward can be redeemed per order. Do you want to replace the current reward?',
  pickup: 'Pickup',
  curbside: 'Curbside',
  delivery: 'Delivery',
  list: 'List',
  map: 'Map',
  open_24_hours: 'Open 24 hours',
  hours: 'Hours',
  who_is_picking: "WHO'S PICKING UP?",
  where_to_deliver: 'WHERE TO DELIVER',
  use_current_location: 'Use your current location?',
  your_bag_is_empty: 'YOUR BAG IS EMPTY',
  total: 'TOTAL',
  estimated_tax: 'ESTIMATED TAX',
  sales_tax: 'Sales Tax',
  service_fee: 'Service Fee',
  delivery_fee: 'DELIVERY FEE',
  subTotal: 'Sub Total',
  success: 'SUCCESS',
  duplicate_items_added: 'Duplicate item added to cart.',
  item_removed_from_cart: '1 item removed from cart.',
  order_detail: 'ORDER DETAILS',
  required: 'Required',
  bar_code_should_not_be_empty: 'Barcode should be at least 12 digits',
  yes: 'Yes',
  no: 'No',
  redeem_in_restaurant: 'Redeem in Restaurant',
  my_rewards: 'MY REWARDS',
  how_to_redeem_your_rewards: 'HOW TO REDEEM YOUR REWARDS',
  redeem_in_restaurant_through_qr_code:
    'Click "Redeem in Restaurant" above and then scan the QR code at the register.',
  you_got: "You've Got",
  available_rewards: 'Available ApplyRewards',
  redeem_points: 'REDEEM POINTS',
  place_order: 'PLACE ORDER',
  add_credit_Card: 'add a credit/debit card',
  edit_credit_card: 'Edit Credit Card',
  update_credit_card: 'Update Credit Card',
  add_gift_card: 'Add Gift Card',
  change: '(CHANGE)',
  pickup_time: 'PICKUP TIME',
  who_z_picking_up: "WHO'S PICKING UP?",
  no_slots_available: 'No slots available',
  asap: 'ASAP',
  no_more_slots_available: 'No more slots available',
  more_time: 'More Time',
  change_location: 'Change Location',
  location_changed_to: 'LOCATION CHANGED TO',
  sorry_some_items_may_not_available: "SORRY, SOME ITEMS AREN'T AVAILABLE AT YOUR NEW LOCATION.",
  cancel_location_change: 'CANCEL LOCATION CHANGE',
  keep_original_location: 'KEEP ORIGINAL LOCATION',
  change_location_uc: 'CHANGE LOCATION',
  confirm_uc: 'CONFIRM',
  remaining_amount: 'Remaining Amount',
  default: 'Default',
  delete: 'Delete',
  make_default: 'Make Default',
  change_payment_method: 'Change Payment Method',
  do_you_really_want_to_remove_this_card: 'Do You Really Want To Remove This Card?',
  add_credit_Card_account:
    'To add a credit card to your account, place an order and enter the gift card information during checkout.',
  add_gift_card_account:
    'To add a gift card to your account, place an order and enter the gift card information during checkout.',
  no_addresses_string: "You don't have any delivery addresses",
  notificarion_toggle_text:
    'Keep up to date on rewards, exclusive offers and new product launches.',
  email_notification: 'Email Notificationn',
  push_notification: 'Push Notification',
  rewards: 'Rewards',
  recent_orders: 'Recent Orders',
  date: 'Date',
  category: 'Category',
  activity: 'Activity',
  order_id: 'Order ID',
  amount: 'Amount',
  pickup_location: 'Pickup Location',
  restaurant_location: 'Restaurant Location',
  invite_heading: 'GIVE $5 , GET $5',
  earn_through_invite:
    'Earn $5 off when your friends use the invite code below to Sign Up for Rubio’s MyRewards and make their first purchase.',
  tap_to_copy: 'Tap to copy : ',
  no_points: "You don't have any Points",
  no_rewards: "You don't have any MyRewards",
  i_accept: 'I accept the',
  terms_and_conditions: 'Terms and Conditions.',
  signup: 'Sign up',
  password_must_match: 'Password does not match',
  delivery_time: 'Delivery Time',
  create_password: 'Create Password*',
  view_account: 'View Account',
  done: 'Done',
  your_rewards: 'Your MyRewards',
  earn_rewards: 'Earn MyRewards',
  you_ve_earned_rewards_for_rubios: "You've earned points for Free Rubio's!",
  you_can_case_in_rewards:
    "You can cash in your points for free food when you get to 400, 700 or 1300 points. So keep enjoying your Rubio's favorites - tasty rewards are coming your way!",
  you_are_all_set: 'You’re all set!',
  you_have_received_credit_for_order:
    'You’ve received credit for today’s order and are one step closer to earning your next reward.',
  get_five_dollar_off: 'GET $5 OFF YOUR NEXT ORDER',
  join_rubios_for_rewards: 'Join Rubio’s MyRewards today to start earning rewards.',
  we_will_bring_food_shortly: 'We’ll bring your food right to you shortly.',
  we_will_take_it_from_here: "WE'LL TAKE IT FROM HERE. SEE YOU SOON.",
  congratulations: 'Congratulations!',
  welcome_text: "Welcome to RUBIO'S REWARDS",
  firstOrder: 'Begin your order to start earning rewards today!',
  order_now: 'Order Now',
  welcome_back: 'Welcome Back!',
  edit_order: 'Edit Order',
  reorder: 'ReOrder',
  your_favourite_location: 'Your favourite Location',
  dine_in: 'Dine In',
  table_number: 'Table Number',
  who_z_ordering: "Who's ordering?",
  i_want_contactless_delivery: 'I want contactless delivery',
  please_provide_your_feedback_for_this_order: 'Please provide your feedback for this order',
  skip: 'Skip',
  next: 'Next',
  login: 'Log in',
  email_address: 'Email Address',
  password: 'Password',
  dont_have_account: "Don't have an account?",
  send_instructions: 'Send',
  reset_password_info:
    'Create an 8-16 character password that has letters, numbers, and special characters.',
  setup_account: 'Let’s set up your account!',
  first_name: 'First Name',
  last_name: 'Last Name',
  continue: 'Continue',
  send_code: 'Send Code',
  verify: 'Verify',
  complete: 'Complete',
  mobile_number: 'Mobile Number',
  enter_mobile: 'Enter Mobile Number',
  phone_verification_info:
    'Enter Phone number for verification and to use your phone number at the register to earn your points',
  agree_to_receive_sms: 'I agree to receive SMS messages',
  verification_instructions: 'Complete your registration by verifying the code sent to ',
  birthday_placeholder: 'MM/DD',
  birthday_rewards: 'Birthday (Optional)',
  birthday_instructions: 'Add your birthday so your gift is on us!',
  fav_location_message: 'Choose your favorite store to view special menu',
  add_fav_location: 'Add favorite location',
  invite_code_message:
    'If you received a code from your friend, enter it here to get a special offer for both of you.',
  did_a_friend_gift_you_a_code: 'Did a friend give you a code? ',
  enter_it_here: 'Enter it here!',
  referral_code: 'Invite Code ',
  enter_referral_code: 'Enter Invite Code',
  did_your_friend: 'Did a friend give you a code? Enter it here!',
  back_to_login: 'Back to Login',
  we_have_sent_instructions_to_your_mail: 'We have sent password reset instructions to your email.',
  check_your_email: 'Check your email',
  open_email_app: 'Open email app',
  resend_email: 'Re-send email',
  resend_email_in: 'Re-send email in ',
  email: 'Email',
  allow: 'Allow',
  open_email: 'Open Email App',
  my_rewardss: 'My MyRewards',
  favourite_store: 'Favorite Store',
  payment_methods: 'Payment Methods',
  my_profile: 'My Profile',
  my_Rewards_chanllenges: 'My Rewards & Challenges',
  guest_login_modal_text: 'Login or create an account to earn points and start challenges!',
  guest_login_modal_text_my_orders:
    'Create an account to save your delivery\n location, and add payment methods.',
  guest_login_modal_text_my_fav:
    'Login or create an account to save a meal\n as your favorite and easily reorder!',
  already_a_member: 'Already a member?',
  login_: 'Login',
  reset_password_: 'RESET',
  under_dev: 'Screen is currently in development',
  my_orders: 'My \n Orders',
  my_fav: 'My \n favorites',
  scan_modal_text: 'Scan MyRewards Card',
  points_balance: 'Points Balance',
  pick_up_in_store: 'Pick Up In Store',
  prepare_now: 'Prepare Now',
  add_more_menu_items: 'Add more menu items',
  salsa_bar_text_one: 'Spice it up with free items from the ',
  salsa_bar_text_two: 'Salsa Bar',
  include_napkin: 'Include Napkins & Utensils',
  my_orders_: 'My Order',
  customize: 'Customize',
  delivery_order: 'Delivery Order',
  street_address_: 'Street Address',
  aptFloor_optional: 'Enter Apt, Floor, Building (Optional)',
  zipCode: 'Zip Code',
  add_a_new_address: 'ADD A NEW ADDRESS',
  enter_mobile_umber: 'Enter Mobile Number',
  redeem: 'Redeem',
  reOrder: 'Reorder',
  save: 'save',
  fav_order_name_placeholder: 'Enter Nickname',
  add_a_card: 'add a card',
  no_order_yet: 'No order history yet...\n' + 'Order now and start earning points!',
  no_fav_order_yet:
    ' No favorite yet...\n' +
    'Go to MY ORDERS to add a order to Favorites for future easy reordering!',
  no_item_in_cart: 'Your bag is currently empty...\n' + 'Order now and start enjoy delicious!',
  no_fav_store_selected_yet: '',
  five_dollars_off: '$5 off your first order',
  ten_points: '10 points for every $1 spent',
  earn_bonus_points: 'Earn bonus points throughout the year',
  birthday_surprise: 'Special birthday surprises',
  go_to_rewards: 'go to rewards',
  add_newDelivery_address_heading: 'To Add a New Address:',
  add_newDelivery_address_subText:
    'Place a new order, add the new delivery address and then select "Set as default."',
  rewards_onboarding_screen_1_text_1:
    'Click the scan button on the home screen and scan the QR code at the register before payment.',
  rewards_onboarding_screen_1_text_2:
    "You'll automatically earn points for orders placed through the app when you're logged in.",
  app_order: 'APP ORDERS',
  redeem_in_store: 'TO REDEEM IN-STORE',
  rewards_onboarding_screen_2_text_1:
    'Find the reward you\'d like to use and click "Scan In-Store." Scan the QR code on the next screen to redeem your reward.',
  rewards_onboarding_screen_2_text_2:
    'Place your order as usual and select from the available rewards on the checkout screen',
  redeem_in_app: 'TO REDEEM IN-APP',
  you_have_got: 'You’ve Got',
  about_rubios_program: 'About Rubio’s \nRewards Program',
  orderInProgress: 'Order in Progress',
  deliveryOrder: 'Check your text messages for live DoorDash tracking info.',
  pickupOrder: 'Store has received your order',
  rewards_are_on_the_way: 'REWARDS POINTS ARE ON THE WAY!',
  points_are_on_the_way: 'POINTS ARE ON THE WAY!',
  passwordInstructions:
    'Password must be 8-16 characters and include a letter, number and special character.',
  phonenumberInstructions: 'Enter new phone number for verification.',
  inviteFriends: 'INVITE FRIENDS',
  scheduled_for: 'Scheduled For',
  scan_reciept: 'Scan Receipt',
  enter_qr_code: 'Enter QR Code',
  invite_instructions: '$5 for you, $5 for your friend!',
  invite_instructions_:
    'Invite your friends to join - they’ll get $5 when they join and you’ll get $5 when they complete their first order!',
  copy_your_code: 'Copy Your Code',
  recieve_instructions:
    'You will receive $5 dollars after your friend completes their first order.',
  select_your_store: 'Select your store',
  search_by_city_state_zip: 'Search by city, zipcode, and state',
  search_placeholder: 'Search by City/State or ZIP Code',
  provide_a_phone_number:
    'Please provide a phone number in case the restaurant needs to contact you about your order.',
  no_reusult_mateched: 'No result Matched',
  screen_name_filter: 'screen',
  select_order_type: 'select_order_type',
  select_location: 'select_location',
  select_past_order: 'select_past_order',
  select_item: 'select_item',
  product_details: 'product_details',
  view_cart: 'view_cart',
  add_to_cart_log_event: 'add_to_cart',
  remove_from_cart: 'remove_from_cart',
  home_screen: 'Home Screen',
  click: 'click',
  add_address_log: 'add_address',
  communication_copy: 'Receive news, updates and special offers from Rubio’s.',
  update_address: 'Update Address',
  challenge_Completed: 'Challenge Completed',
  no_history_available: 'No History Available',
  add_payment_info: 'add_payment_info',
  purchase: 'purchase',
  view_item: 'view_item',
  begin_checkout: 'begin_checkout',
  bar_code: 'Enter Receipt Barcode',
  barcode_receipt_number: 'Enter the numeric code at the bottom of your receipt to earn points!',
  enter_verification_code: 'Enter Verification Code',
  verification_code: 'Verification Code',
  password_instructions:
    'Password must be at least 8 characters and must include a letter, number, and a special character.',
  favourite_restaurant: 'Favourite Restaurant',
  favourite_restaurant_message: 'Choose your favorite restaurant.',
};
