
//It is recommended to not change the screen name values. Screen names are used in firebase logs.
export const screens = {
  SIGNUP: 'Sign Up',
  FORGOT_PASSWORD: 'Reset Password',
  RESET_PASSWORD: 'ResetPassword',
  LAST_ONBOARDING: 'Last OnBoarding',
  SIGN_IN: 'Sign_in',
  LOCATION: 'Location',
  LOCATION_LISTING: 'LocationListing',
  MENU: 'Menu',
  PRODUCT: 'Product',
  CHECKOUT: 'Checkout',
  CART: 'Cart',
  REWARDS: 'My Rewards',
  ACCOUNT: 'Account',
  REWARD_QR_CODE: 'ScanQRCode',
  HELP: 'RewardHelp',
  CHECK_IN: 'CheckIn',
  MY_ORDERS: 'My Orders',
  MY_ORDER_DETAIL: 'Order Details',
  DELIVERY_ADDRESSES: 'Delivery Address',
  PAYMENT_METHODS: 'Payment Methods',
  PROFILE: 'My Profile',
  ACCOUNT_HISTORY: 'Account History',
  INVITE_FRIENDS: 'Refer a Friend',
  WELCOME_SCREEN: 'Welcome Screen',
  CHALLENGES: 'Challenges',
  CHALLENGE_DETAIL: 'Challenge Details',
  ON_BOARDING_SCREEN: 'OnBoarding Screen',
  ORDER_FEEDBACK: 'ORDER FEEDBACK',
  CHECK_YOUR_MAIL: 'Check Your Mail',
  CHOOSE_STORE: 'Choose Store',
  MENU_CATEGORIES: 'Menu Categories',
  UNDER_DEV_SCREEN: 'Under Dev Screen',
  HOME_SCREEN: 'Home Screen',
  CHOOSE_ORDER_TYPE: 'Choose Order Type',
  DELIVERY_FLOW: 'Delivery Flow',
  MY_FAVOURITE: 'My Favourite Orders',
  MY_FAV_STORE: 'My Favorite Store',
  REWARDS_ONBOARDING: 'Rewards OnBoarding',
  SOCIAL_SIGNUP_COMPLETE_PROFILE: 'Social Signup Complete Profile',
  DELIVERY_STATUS: 'Delivery Status',
  SCAN_RECIEPT: 'Scan Receipt',
  NOTIFICATIONS: 'Notifications',
  ENTER_QR_CODE: 'Enter QR Code',
};
