export const HOME_PAGE_CATEGORIES = [
  'FEATURED ITEMS',
  'SEASONAL MENU',
  'TACO PLATES',
  'BURRITOS',
  'BOWLS & SALADS',
  'QUESADILLAS AND NACHOS',
  'FAMILY MEALS',
  'KIDS',
  'DRINKS',
  'SIDES & EXTRAS',
  'DESSERTS',
  'TACOS A LA CARTE',
];

export const CATERING_CATEGORIES = [
  'CATERING TACO BARS',
  'CATERING BURRITOS',
  'CATERING BOWL BAR',
  'CATERING SALADS',
  'CATERING APPETIZERS',
  'CATERING DRINKS',
  'CATERING DESSERTS',
  'CATERING SIDES',
  'CATERING PACKAGES',
];
