export enum challengesType {
  GET_CHALLENGES = 'GET_CHALLENGES',
  GET_CHALLENGES_SUCCESS = 'GET_CHALLENGES_SUCCESS',
  GET_CHALLENGES_FAILURE = 'GET_CHALLENGES_FAILURE',

  GET_CHALLENGE_DETAIL = 'GET_CHALLENGE_DETAIL',
  GET_CHALLENGE_DETAIL_SUCCESS = 'GET_CHALLENGE_DETAIL_SUCCESS',
  GET_CHALLENGE_DETAIL_FAILURE = 'GET_CHALLENGE_DETAIL_FAILURE',
  CLEAR_CHALLENGE_DETAIL = 'CLEAR_CHALLENGE_DETAIL',
}
