export enum accountHistoryTypes {
  GET_ACCOUNT_HISTORY = 'GET_ACCOUNT_HISTORY',
  GET_ACCOUNT_HISTORY_SUCCESS = 'GET_ACCOUNT_HISTORY_SUCCESS',
  GET_POINT_HISTORY_SUCCESS = 'GET_POINT_HISTORY_SUCCESS',
  GET_ACCOUNT_HISTORY_FAILURE = 'GET_ACCOUNT_HISTORY_FAILURE',
}
