export enum productOptionActionsTypes {
  GET_PRODUCT_OPTION_REQUEST = 'GET_PRODUCT_OPTION_REQUEST',
  GET_PRODUCT_OPTION_SUCCESS = 'GET_PRODUCT_OPTION_SUCCESS',
  GET_PRODUCT_OPTION_FAILURE = 'GET_PRODUCT_OPTION_FAILURE',
  RESET_PRODUCT_OPTIONS = 'RESET_PRODUCT_OPTIONS',
  SET_EXPANDED_MODIFIERS = 'SET_EXPANDED_MODIFIERS',
  RESET_EXPANDED_MODIFIERS = 'RESET_EXPANDED_MODIFIERS',
  SET_CHECKED_MODIFIERS = 'SET_CHECKED_MODIFIERS',
  RESET_CHECKED_MODIFIERS = 'RESET_CHECKED_MODIFIERS'
}
